#!/bin/bash

# SIU Assignment Fix - Backend Restart Script

echo "=== BACKEND RESTART PROCEDURE ==="
echo "The backend server failed to start due to port 8080 being in use."
echo "Your fixes haven't been applied yet because the server isn't running."
echo ""
echo "STEP 1: Kill existing Java processes on port 8080"
echo "Run one of these commands in Command Prompt (as Administrator):"
echo ""
echo "Option A: Kill by port (Windows)"
echo "netstat -ano | findstr :8080"
echo "# Note the PID number, then:"
echo "taskkill /PID [PID_NUMBER] /F"
echo ""
echo "Option B: Kill all Java processes"
echo "taskkill /IM java.exe /F"
echo ""
echo "STEP 2: Start the backend server"
echo "cd FireInsurance-Backend"
echo "./mvnw spring-boot:run"
echo ""
echo "STEP 3: Wait for startup message"
echo "Look for: 'Started FireInsuranceApplication in X.XXX seconds'"
echo ""
echo "STEP 4: Test SIU assignment again"
echo "The error should now be fixed!"
echo ""
echo "=== WHY THIS FIXES THE ERROR ==="
echo "- HTTP 200 but ok:false means malformed JSON response"
echo "- This happens when old code (without fixes) is still running"
echo "- Our SecurityConfig, Entity, and Controller fixes need the new server"
echo ""